#!/bin/bash

usage() {

  echo "Usage cis_cron:"
  echo ""
  echo 'cis_cron <--add | -a > <cron_exp> </project/job>    to add job into sheduled tasks'
  echo 'cis_cron <--del | -d > <cron_exp> </project/job>    to delete job from sheduled tasks'
  echo 'cis_cron <–-list | -l > [mask]                      to list sheduled tasks'
  echo ""
  echo "Where cron_exp is regular crontab expression, i.e.: '*/2 * * * *'"
  echo ""

  return 0
}


if [ "x$cis_base_dir" = "x" ]
then

  echo ""
  echo "FATAL: the base dir for CI system hasn't defined. Please define it in environment variable \"cis_base_dir\""
  echo "Execution aborted."
  echo ""
  exit 3

fi

if [ $# -lt 1 ]
then

  usage
  exit 65

fi


operation=$1

case "$operation" in

  "--list" | "-l")
  
    echo "cis sheduled tasks list for $cis_base_dir is:"
    exit 0
  ;;



  "--del" | "-d")
  
    shift

    if [ $# -eq 2 ]
    then

      exit 0

    else

      usage
      exit 1

    fi

  ;;



  "--add" | "-a")
  
    shift

    if [ $# -eq 2 ]
    then

      exit 0

    else

      usage
      exit 1

    fi

  ;;



  *)

    usage
    exit 65

  ;;

esac


