#!/bin/bash

base_dir=$cis_base_dir

value_name=$1

values_file="$base_dir/sessions/$session_id.dat"



while read -r str || [ -n "$str" ]
do
  
  str_value_name=$(echo $str | awk -F "=" '{print $1}')

  str_value=$(echo $str | awk -F "=" '{print $2}')


  if [ "$str_value_name" = "$value_name" ]
  then

    echo "$str_value"
    exit 0;

  fi
done  <$values_file


echo ""
exit 0
