#!/bin/bash

base_dir=$cis_base_dir

param_name=$1

param_value=$2



params_file="$base_dir/sessions/$session_id.prm"

tmp_file="$base_dir/sessions/$session_id.prm$$"

echo "" >$tmp_file



param_was_set=false

while read -r str || [ -n "$str" ]
do
  
  str_param_name=$(echo $str | awk -F "=" '{print $1}')

  if [ -z "$str_param_name" ]
  then
    continue
  fi


  if [ "$str_param_name" = "$param_name" ]
  then

    echo "$param_name=$param_value" >>$tmp_file

    param_was_set=true

  else

    echo "$str" >>$tmp_file

  fi
done  <$params_file


if [ "$param_was_set" = false ]
then

  echo "$param_name=$param_value" >>$tmp_file

fi


$base_dir/core/sessionlog "action=set_call_param param_name=$param_name param_value=\"$param_value\" pid=$$ ppid=$PPID"



mv $tmp_file $params_file

exit 0
